config/routes.rb
Bacon::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get "login", to: "devise/sessions#new", as: :login
    get "logout", to: "devise/sessions#destroy", as: :logout
  end

  match '/organizations/check_url' => 'organizations#check_url'
  match '/organizations/switch_month' => 'organizations#switch_month'
  match '/account' => 'users#edit'
  match '/upload' => 'organizations#upload'
  match '/welcome' => 'organizations#welcome'
  match '/organizations/:id/delete_demo_projects' => 'organizations#delete_demo_projects', as: :delete_demo_projects
  match '/users/:id/delete_account' => 'users#delete_account', as: :delete_account

  resource :user, only: [:edit] do
    collection do
      put 'update'
    end
  end

  resources :plans

  resources :organizations, :except => [:index] do
    get "search" => 'organizations#search', :on => :member
    # post :upload, :on => :member
    get ":year/:month" => "organizations#show", constraints: {
        year:       /\d{4}/,
        month:      /\d{1,2}/
    }
  end
  # resources :organizations, :except => [:index] do
  resources :projects do
    post :update_status
    resources :payments, :only => :create
    resources :notes, :only => [:create, :destroy, :update]
    resources :project_contacts
  end
  resources :contacts do
    post :filter, :on => :collection
    get :hover, :on => :member
  end
  resources :categories do
    post :update_color, :on => :member
  end
  # end
  resources :payments
  resources :notes

  match '/api/create_user' => 'api#create_user'
  match '/api/update_user' => 'api#update_user'
  match '/api/delete_user' => 'api#delete_user'
  match '/api/users/validate' => 'api#validate_user'
  match '/api/check_url' => 'api#check_url'

  match '/feedbacks' => 'feedbacks#index'
  root :to => 'organizations#show'

  default_url_options :host => 'incomehawkapp.com'
end

app/views/shared/_sidebar_add_buttons.html.haml
.right-col-block
  %ul.action-buttons
    %li.green-button
      = link_to "Add Project", new_project_path, :class => 'add-project'
    %li.blue-button
      = link_to "Add Contact", new_contact_path, :class => 'add-contact'

app/views/shared/_sidebar_billed_payments.html.haml
- if @billed_payments.size > 0
  #billed-payments.right-col-block
    %h3.block-title Billed Payments
    .payment-group
      %ul.payment-list
        - @billed_payments.each do |p|
          = render :partial => 'sidebar/payment', :locals => {:payment => p}

app/views/shared/_sidebar_dashboard.html.haml
- sidebar :add_buttons, :upcoming_payments, :overdue_payments

app/views/shared/_sidebar_overdue_payments.html.haml
- if @overdue_payments.size > 0
  #overdue-payments.right-col-block
    %h3.block-title Overdue Payments
    .payment-group
      %ul.payment-list
        - @overdue_payments.each do |p|
          = render :partial => 'sidebar/payment', :locals => {:payment => p}

app/views/shared/_sidebar_tip.html.haml
#tips.right-col-block
  %h3.block-title Tip
  .tip
    %p
      %strong Active Projects
      are projects that you’re currently working on.
    %p
      %strong Prospective Projects
      are projects that you’re currently bidding on but aren’t finalized yet.
    %p
      %strong Lost projects
      are where unsuccessful prospective projects go. Make sure this doesn’t rise to high
    %p
      %strong Completed projects
      are successful projects that all payments have been completed and aren’t relevant for the coming months – you can always activate a project if some more work is needed.

app/views/shared/_sidebar_tip_contacts.html.haml
#tips.right-col-block
  %h3.block-title Tip
  .tip
    %p 
      %strong Tip#1:
      Enter what you know: either first, last, or company name…just one is required.
    %p 
      %strong Tip#2:
      Be sure to add logos for you contacts to make them easy to find

app/views/shared/_sidebar_upcoming_payments.html.haml
- if @upcoming_today_payments.size > 0 || @upcoming_tomorrow_payments.size > 0 || @upcoming_next_week_payments.size > 0
  #upcoming-payments.right-col-block
    %h3.block-title Upcoming Payments
    - if @upcoming_today_payments.size > 0
      #today.payment-group
        %h4 Today
        %ul.payment-list
          - @upcoming_today_payments.each do |p|
            = render :partial => 'sidebar/payment', :locals => {:payment => p}
    - if @upcoming_tomorrow_payments.size > 0
      #tomorrow.payment-group
        %h4 Tomorrow
        %ul.payment-list
          - @upcoming_tomorrow_payments.each do |p|
            = render :partial => 'sidebar/payment', :locals => {:payment => p}
    - if @upcoming_next_week_payments.size > 0
      #next-week.payment-group
        %h4 Next Week
        %ul.payment-list
          - @upcoming_next_week_payments.each do |p|
            = render :partial => 'sidebar/payment', :locals => {:payment => p}