config/routes.rb
Bacon::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get "login", to: "devise/sessions#new", as: :login
    get "logout", to: "devise/sessions#destroy", as: :logout
  end

  match '/organizations/check_url' => 'organizations#check_url'
  match '/organizations/switch_month' => 'organizations#switch_month'
  match '/account' => 'users#edit'
  match '/upload' => 'organizations#upload'
  match '/welcome' => 'organizations#welcome'
  match '/organizations/:id/delete_demo_projects' => 'organizations#delete_demo_projects', as: :delete_demo_projects
  match '/users/:id/delete_account' => 'users#delete_account', as: :delete_account

  resource :user, only: [:edit] do
    collection do
      put 'update'
    end
  end

  resources :plans

  resources :organizations, :except => [:index] do
    get "search" => 'organizations#search', :on => :member
    # post :upload, :on => :member
    get ":year/:month" => "organizations#show", constraints: {
        year:       /\d{4}/,
        month:      /\d{1,2}/
    }
  end
  # resources :organizations, :except => [:index] do
  resources :projects do
    post :update_status
    resources :payments, :only => :create
    resources :notes, :only => [:create, :destroy, :update]
    resources :project_contacts
  end
  resources :contacts do
    post :filter, :on => :collection
    get :hover, :on => :member
  end
  resources :categories do
    post :update_color, :on => :member
  end
  # end
  resources :payments
  resources :notes

  match '/api/create_user' => 'api#create_user'
  match '/api/update_user' => 'api#update_user'
  match '/api/delete_user' => 'api#delete_user'
  match '/api/users/validate' => 'api#validate_user'
  match '/api/check_url' => 'api#check_url'

  match '/feedbacks' => 'feedbacks#index'
  root :to => 'organizations#show'

  default_url_options :host => 'incomehawkapp.com'
end

app/models/project.rb
class Project < ActiveRecord::Base
  ## Extensions ##

  ## fields ##
  STATUSES = ["Active", "Prospective", "Lost", "Completed"]
  MAX_LIMIT = 5
  attr_accessor :contact

  ## associations ##
  belongs_to :organization
  belongs_to :category
  has_and_belongs_to_many :user
  has_many :payments, dependent: :destroy, :order => "start_date DESC"
  has_many :membershipments
  has_many :members, through: :membershipments, :class_name => "User"
  has_many :notes, order: "created_at DESC"
  has_and_belongs_to_many :contacts

  accepts_nested_attributes_for :payments
  delegate :plan_id, :plan, to: :organization

  ## callbacks ##

  ## validations ##
  validates :name, :organization, :status, :category_id, presence: true
  validate :category_id_non_zero
  validates :status, inclusion: { in: STATUSES }
  validate :plan_limits, on: :create

  def plan_limits
    o = organization
    if o.plan_id.present?
      if o.projects.count >= plan.max_projects && plan.max_projects > 0
        errors.add(:plan_limit, "You have reached limit of projects for your plan(#{plan.max_projects}). <a href='#'>Upgrade?</a>")
      end
    end
  end

  ## named scopes ##
  STATUSES.each do |status|
    define_singleton_method status.downcase do
      where("status = '#{status}'")
    end
  end
  scope :recent, lambda {|n| order('created_at DESC').limit(n)}
  scope :search_for, lambda {|term| term = "%#{term.downcase}%"
  where(["LOWER(name) LIKE ? OR LOWER(description) LIKE ? OR LOWER(status) LIKE ?", term, term, term]) }


  ## methods ##
  def payment
    payments.build
  end

  STATUSES.each do |st|
    define_method st.downcase+"?" do
      self.status == st
    end
  end

  def estimated
    if active? || completed?
      payments.collect(&:total_value).sum
    else
      estimated_value
    end
  end

  def estimated_value
    self.attributes['estimated_value'] || 0
  end

  def billed
    payments.collect(&:billed_value).sum
  end

  def remaining
    payments.collect(&:remaining_value).sum
  end

  def payment_progress
    unless estimated == 0
      ((billed / estimated)*100).to_i
    else
      0
    end
  end

  def update_status(nstatus, update_payments = false)
    if nstatus == "Prospective" || nstatus == "Lost"
      self.estimated_value = estimated
    elsif nstatus == "Completed"
      if update_payments
        payments.each {|p|
          p.completed = true
          p.save!
        }
      end
    end
    self.status = nstatus
    save!
  end

  def self_errors
    errors.delete(:organization)
    errors
  end

  class << self
    include Rails.application.routes.url_helpers

    def json_data(projects)
      projects.collect{|x|
        {:label => x.name, :category => 'Projects', :desc => x.status, :href => project_path( x)}
      }
    end

    def demo_projects
      where(['projects.demo = ?', TRUE])
      .order('start_date ASC')
    end
  end


  private

  def category_id_non_zero
    if category_id == 0
      errors.add :base, "Can't create project without category"
      false
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  inherit_resources
  before_filter :fetch_tabs
  respond_to :js, :html

  rescue_from ActiveRecord::RecordNotFound do |ex|
    redirect_to '/'
  end

  layout 'garden'
  nested_belongs_to :organization

  def show
    @project = Project.includes(:category, :notes => :user).find(params[:id])
    @organization = @project.organization
  end

  def index
    max_projects = Project::MAX_LIMIT
    @status = params[:status] || "Active"
    @page = params[:page] ? params[:page].to_i : 0
    @projects = @organization.projects.includes(:payments, :notes, :category).where(["status = ?", @status])
    unless @page == 0
      @projects = @projects.limit(max_projects).offset(@page*max_projects)
    end

    # expand collapse
    @projects_count = @organization.projects.where(["status = ?", @status]).count
    @diff = @projects_count - (@page+1)*max_projects
    if @diff == max_projects
      @has_next_page = true
      @page += 1
    elsif @diff < max_projects && @diff > 1
      @has_next_page = true
      @projects_left = @diff
      @page += 1
    elsif @diff > max_projects
      @has_next_page = true
      @page += 1
    elsif @diff < 1
      @has_next_page = false
    end
    @projects = @projects.to_a
  end

  def update_status
    status = params[:status]
    update_payments = params[:update_payments]
    @project = Project.find(params[:project_id])
    @project.update_status(status, update_payments == '1')
    respond_to do |format|
      format.js
    end
  end

  def create
    @project = @organization.projects.build(params[:project])
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project }
      else
        format.html { render :new }
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def render_project(project)
    render :partial => "projects/#{project.status.downcase}_project", :locals => {:project => project}
  end

  def render_project_overview(project, show_status = false)
    render :partial => "projects/#{project.status.downcase}_project_overview", :locals => {:project => project, :show_status => show_status}
  end

  def render_projects_header(projects)
    proj = projects.first
    return unless proj
    render :partial => "projects/#{proj.status.downcase}_projects_header", :locals => {:projects => projects}
  end

  def progress_bar(percent)
    per_class = (percent/10).to_i*10
    per_class = "33" if (33..39).include? percent
    per_class = "66" if (66..69).include? percent
    content_tag :div, percent, :class => "bar-inner per#{per_class}"
  end
  
  def status_button_active(cls, project)
    "active" if cls == project.status.downcase
  end
end

app/views/projects/_active_project.html.haml
%li.project-row
  .project-name
    = link_to project_path( project.id) do
      %h5= project.name
      - if project.category
        .category{:style => "background:"+project.category.color}= project.category
  .project-valued
    .number= p(project.estimated)
    %label{:for => ""} Valued
  .project-billed
    .number= p(project.billed)
    %label{:for => ""} Billed
  .project-remaining
    .number= p(project.remaining)
    %label{:for => ""} Remaining
  .project-payments
    .number= project.payments.length
    %label{:for => ""} Payments
  .project-progress
    .bar-outer
      = progress_bar(project.payment_progress)
    %label{:for => ""}= per project.payment_progress

app/views/projects/_completed_project.html.haml
%li.project-row
  .project-name
    = link_to project_path( project.id) do
      %h5= project.name
      - if project.category
        .category{:style => "background:"+project.category.color}= project.category
  .project-valued
    .number= p(project.estimated)
    %label{:for => ""} Valued
  .project-billed
    .number= p(project.billed)
    %label{:for => ""} Billed
  .project-remaining
    .number= p(project.remaining)
    %label{:for => ""} Remaining
  .project-payments
    .number= project.payments.length
    %label{:for => ""} Payments
  .project-progress
    .bar-outer
      = progress_bar(project.payment_progress)
    %label{:for => ""}= per project.payment_progress

app/views/projects/_completed_projects_header.html.haml
- estimated = projects.sum{|x| x.estimated || 0}
- billed = projects.sum{|x| x.billed || 0}
- remaining = projects.sum{|x| x.remaining || 0}
- progress = estimated == 0 ? 0 : ((billed/estimated)*100).to_i
.number-of-projects
  .number= projects.count
  %label{:for => ""} Projects
.valued-projects
  .number= p estimated
  %label{:for => ""} Valued
.billed-projects
  .number= p billed
  %label{:for => ""} Billed
.remaining-projects
  .number= p remaining
  %label{:for => ""} Remaining
.completed
  .bar-outer
    = progress_bar progress
  %label{:for => ""}
    = per progress
    Completed

app/views/projects/_contact_hover.html.haml
.contact-hover{:id => "contact-hover-#{contact.id}"}
  %h1.contact-name= contact.name
  %h2.contact-company= contact.organization_name
  .contact-logo
    = image_tag contact_avatar(contact), :class => 'logo-preview'
  %ul.contact-details-group
    %li.contact-email
      %span.label Email Address
      %a{:href => "mailto:#{contact.email}"}= contact.email
    - unless contact.website.blank?
      %li.contact-website
        %span.label Website Address
        %a{:href => "#{contact.website}"}= contact.website
    - unless contact.work_phone.blank?
      %li.contact-phone
        %span.label> Cell Phone Number
        = contact.work_phone
    - unless contact.home_phone.blank?
      %li.contact-cell
        %span.label> Phone Number
        = contact.home_phone
  - if !contact.no_address
    %ul.contact-details-group
      %li.contact-address
        %span.label> Address
        = raw contact.address_full
    .tri

app/views/projects/_form_contacts.html.haml
= f.semantic_fields_for :contact do |fc|
  %li.form-item#input-project-contact
    = fc.label :name, "Contacts", :class => 'form-label'
    = f.select :contact_ids, @organization.contacts_list, {}, :class => 'contacts-select', :id => 'input-project-contact-field', :multiple => true, "data-placeholder" => "Add contacts for a project"
    = link_to 'Create new Contact', new_contact_path( :format => :js), :rel => "facebox", :id => 'create_contact_link', :class => 'hidden'
    %p.form-description Which Contacts are connected to this project?

app/views/projects/_lost_project_overview.html.haml
%p
  %h2{:style => "display:inline"}= project.name
  = link_to '(edit)', edit_project_path( project)
  = render :partial => 'projects/project_status_bar', :locals => {:project => project, :show_status => show_status}
- if project.category
  .category{:style => "background:"+project.category.color}= project.category
%br
%ul.project-contacts
  - project.contacts.each do |contact|
    = render :partial => 'projects/contact_light', :locals => {:contact => contact}
.clear
%br
.projects-header            
  .number-of-projects
    .number= project.payments.count
    %label{:for => ""} Payments
  .project-valued
    .number= p(project.estimated)
    %label{:for => ""} Valued
  .project-notes
    .number= project.notes.length
    %label{:for => ""} Notes

app/views/projects/_projects.html.haml
.projects-list
  %ul
    = render projects

app/views/projects/_prospective_project.html.haml
%li.project-row
  .project-name
    = link_to project_path( project.id) do
      %h5= project.name
      - if project.category
        .category{:style => "background:"+project.category.color}= project.category
  .project-valued
    .number= p(project.estimated)
    %label{:for => ""} Valued
  .project-notes
    .number= project.notes.length
    %label{:for => ""} Notes
  .project-updated
    .number= project.updated_at.strftime("%b %e %Y")
    %label{:for => ""} Last updated

app/views/projects/_prospective_project_overview.html.haml
%p
  %h2{:style => "display:inline"}= project.name
  = link_to '(edit)', edit_project_path( project)
  = render :partial => 'projects/project_status_bar', :locals => {:project => project, :show_status => show_status}
- if project.category
  .category{:style => "background:"+project.category.color}= project.category
%br
%ul.project-contacts
  - project.contacts.each do |contact|
    = render :partial => 'projects/contact_light', :locals => {:contact => contact}
.clear
%br
.projects-header
  .number-of-projects
    .number= project.payments.count
    %label{:for => ""} Payments
  .project-valued
    .number= p(project.estimated)
    %label{:for => ""} Valued
  .project-notes
    .number= project.notes.length
    %label{:for => ""} Notes
  .project-updated
    .number= project.updated_at.strftime("%b %e %Y")
    %label{:for => ""} Last updated

app/views/projects/destroy.js.erb
window.location = '/';

app/views/projects/edit.html.haml
- title "Edit Project"
- sidebar "add_buttons", "tip"
- content_for :head do
  -#= include_javascripts :edit_project
  = javascript_include_tag "edit_project"
= render 'form' 

:javascript
  window.organization_id = '#{@organization.id}'
  window.project_id = '#{@project.id}'

app/views/projects/index.html.haml
- title "Projects"
#active-projects.dashboard-project
  %h2.open
    = link_to "#{@status} Projects", '#active-projects-container', class: "toggle-link"
  #active-projects-container
    %div{:class => "#{@status.downcase}-projects-icon"} Projects
    .projects-header
      = render_projects_header(@projects)
    #active-projects-list.projects-list
      %ul
        - @projects.each do |project|
          = render_project project

app/views/projects/show.html.haml
- title "Project"
- content_for :head do
  = javascript_include_tag 'show_project'

#active-projects.dashboard-project
  #active-projects-container
    = render_project_overview(@project, true)

  = render :partial => 'payments/payments', :locals => {:payments => @project.payments}

  = render :partial => 'projects/notes', :locals => {:notes => @project.notes}

:javascript
  window.organization_id = '#{@organization.id}'
  window.project_id = '#{@project.id}'

app/views/projects/update_status.js.erb
<% if @project.status == 'Completed' %> 
  $("#payments-list").html("<%= escape_javascript(render(@project.payments)) %>")
<% end %>
$("#active-projects-container").html("<%= escape_javascript(render_project_overview(@project, true))%> ")
$.ctNotify("Status updated!")
$.fallr('hide')