config/routes.rb
Bacon::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get "login", to: "devise/sessions#new", as: :login
    get "logout", to: "devise/sessions#destroy", as: :logout
  end

  match '/organizations/check_url' => 'organizations#check_url'
  match '/organizations/switch_month' => 'organizations#switch_month'
  match '/account' => 'users#edit'
  match '/upload' => 'organizations#upload'
  match '/welcome' => 'organizations#welcome'
  match '/organizations/:id/delete_demo_projects' => 'organizations#delete_demo_projects', as: :delete_demo_projects
  match '/users/:id/delete_account' => 'users#delete_account', as: :delete_account

  resource :user, only: [:edit] do
    collection do
      put 'update'
    end
  end

  resources :plans

  resources :organizations, :except => [:index] do
    get "search" => 'organizations#search', :on => :member
    # post :upload, :on => :member
    get ":year/:month" => "organizations#show", constraints: {
        year:       /\d{4}/,
        month:      /\d{1,2}/
    }
  end
  # resources :organizations, :except => [:index] do
  resources :projects do
    post :update_status
    resources :payments, :only => :create
    resources :notes, :only => [:create, :destroy, :update]
    resources :project_contacts
  end
  resources :contacts do
    post :filter, :on => :collection
    get :hover, :on => :member
  end
  resources :categories do
    post :update_color, :on => :member
  end
  # end
  resources :payments
  resources :notes

  match '/api/create_user' => 'api#create_user'
  match '/api/update_user' => 'api#update_user'
  match '/api/delete_user' => 'api#delete_user'
  match '/api/users/validate' => 'api#validate_user'
  match '/api/check_url' => 'api#check_url'

  match '/feedbacks' => 'feedbacks#index'
  root :to => 'organizations#show'

  default_url_options :host => 'incomehawkapp.com'
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  RECURRING = ["Fixed", "Hourly", "Monthly"]
  belongs_to :project

  validates :recurring, inclusion: { in: RECURRING }
  validates :rate, :recurring, :start_date, presence: true #:completed
                                                           #validates :number_of_hours,  uniqueness: true, if: lambda { |p| p.recurring == 'Hourly' }
                                                           #validates :number_of_months, uniqueness: true, if: lambda { |p| p.recurring == 'Monthly' }

  attr_accessible :id, :rate, :recurring, :type, :start_date, :completed, :completed_date, :description, :number_of_hours, :number_of_months, :project_id

  before_save :set_billed_at

  scope :unpaid,  where(completed: false)
  scope :paid,    where(completed: true)
  scope :upcoming_today,     -> { unpaid.where(:start_date => DateTime.now.all_day) }
  scope :upcoming_tomorrow,  -> { unpaid.where(:start_date => (DateTime.now + 1.days).all_day) }
  scope :upcoming_next_week, -> { unpaid.where(:start_date => (DateTime.now + 1.weeks).all_week) }
  scope :sidebar_overdue, unpaid.where(['payments.start_date < ?', DateTime.now.to_s(:db)]).order('start_date DESC').limit(5)

  def total_value
    return rate if recurring == "Fixed"
    return rate * number_of_hours if recurring == "Hourly"
    return rate if recurring == "Monthly"
  end

  def billed_value
    completed ? total_value : 0
  end

  def remaining_value
    completed ? 0 : total_value
  end

  def set_billed_at
    self.billed_at = completed ? Time.now : nil
  end

  class << self
    # Scopes
    def this_month_payments(year, month)
      where(['payments.start_date BETWEEN date(?) and date(?)', DateTime.new(year, month).beginning_of_month.to_s(:db), DateTime.new(year, month).end_of_month.to_s(:db)])
      .order('start_date ASC')
    end

    def next_month_payments(year, month)
      where(['payments.start_date BETWEEN date(?) and date(?)', (DateTime.new(year, month) + 1.months).beginning_of_month.to_s(:db), (DateTime.new(year, month) + 1.months).end_of_month.to_s(:db)])
      .order('start_date ASC')
    end

    def last_5_months_payments(year, month)
      where(['payments.start_date BETWEEN date(?) and date(?)', ((DateTime.new(year, month) - 3.months).beginning_of_month).to_s(:db), ((DateTime.new(year, month) + 1.months).end_of_month).to_s(:db)])
    end

    def filter_by_daterange(r_start, r_end)
      where(['payments.start_date between ? and ?',Date.parse(r_start), Date.parse(r_end)])
    end

    def recent_first
      order('start_date DESC')
    end

    def recent_last
      includes(:project).order('start_date ASC')
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  inherit_resources
  before_filter :fetch_tabs
  layout 'garden'
  respond_to :js, :html

  def index
    @payments = @organization.payments.recent_last
    filter_payments
  end

  def update
    @is_updated = params[:payment].has_key?(:completed) ? false : true
    @plain = params[:plain_payment]

    if @plain
      filter_payments
    end

    update!
  end

  def create
    @project = @organization.projects.find(params[:project_id])
    if params[:payment][:recurring] == "Monthly"
      payment_data = []
      params[:payment][:number_of_months].to_i.times do |i|
        pdd = params[:payment].dup
        start_date = DateTime.parse(pdd[:start_date]) + i.months
        if pdd[:completed] == '1'
          completed_date = DateTime.parse(pdd[:completed_date]) + i.months
          pdd[:completed_date] = completed_date.to_s
        end
        pdd[:start_date] = start_date.to_s
        payment_data << pdd
      end
      @payments = payment_data.collect{|pd|
        @project.payments.create(pd)
      }
    else
      @payments = [@project.payments.create(params[:payment])]
    end

    @invalid = @payments.select{|x| !x.valid?}
    if @invalid.size > 0
      @errors = @invalid.collect{|x| x.errors.full_messages}.join(",")
    end

    respond_to do |format|
      format.js
    end
  end

  protected
  
    def filter_payments
      @date_range = params[:date_range]
      @status = params[:status]
      
      if @date_range and !@date_range.empty?
        @payments = filter_by_daterange(@date_range)
      else
        @payments = @organization.payments.recent_last
      end
      
      if @status.present?
        st = @status == '1' ? true : false
        @payments = @payments.where(completed: st)
      end
    end
      
    def filter_by_daterange(date_range)
      r_start, r_end = date_range.split(' - ')
      @organization.payments.recent_last.filter_by_daterange(r_start, r_end)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
  def completed_class(payment)
    payment.completed ? 'payment-completed' : 'payment-not-completed'
  end

  def completed_text(payment)
    payment.completed ? 'Paid' : 'Pending'
  end

  def payment_status_filter_options
    options_for_select([['All', ''], ['Completed', '1'], ['Not completed', '0']])
  end
end

app/views/payments/_list_filters.html.haml
= form_tag payments_path(format: :js), method: :get, remote: true, id: 'payment-filter-form' do
  .payments-date-range
    .form-item
      = text_field_tag :date_range, @date_range, :id => 'payments-range', :placeholder => 'Date Range'
    .form-item.status
      = select_tag :status, payment_status_filter_options, :id => 'payments-status'

app/views/payments/_list_header.html.haml
- estimated = payments.sum{|x| x.total_value || 0}
- billed = payments.select(&:completed).sum{|x| x.total_value || 0}
- remaining = estimated - billed
- progress = estimated == 0 ? 0 : ((billed/estimated)*100).to_i
.number-of-projects
  .number= payments.count
  %label{:for => ""} Payments
.valued-projects
  .number= p estimated
  %label{:for => ""} Valued
.billed-projects
  .number= p billed
  %label{:for => ""} Billed
.remaining-projects
  .number= p remaining
  %label{:for => ""} Remaining
.completed
  .bar-outer
    = progress_bar progress
  %label{:for => ""}
    = per progress
    Completed

app/views/payments/_payment.html.haml
- if defined? ff
  - payment = ff.object
%li.single-payment{:id => "payment_#{payment.id}", :class => "payment-"+completed_text(payment).downcase}
  .payment-completed-icon{:class => completed_class(payment), :payment_id => payment.id}
    %span= completed_text(payment)
  .payment-value
    =p payment.total_value
  .payment-name
    =raw p_description(payment)
  .payment-date
    - day = payment.start_date.day
    = payment.start_date.strftime("#{ActiveSupport::Inflector.ordinalize(day)} %b %Y")
  .payment-type
    = surround '(', ')' do
      = payment.recurring
  .sort-order{:order => payment.start_date.to_i}
  .hover-actions
    = link_to 'Remove Payment', '#', :class => "delete-payment delete-button-small", :payment_id => payment.id
    .payment-edit
      =link_to "edit", '#', :class => 'edit-link'
  .update-payment-wrapper{:payment_id => "#{payment.id}"}
    %input.edit-payment-rate{:type => 'textfield', :value => "#{payment.rate.to_i}", :name => 'payment-rate', :placeholder => 'Rate'}/
    %input.edit-payment-hours{:type => 'textfield', :value => "#{payment.number_of_hours.to_i}", :name => 'payment-number_of_hours', :placeholder => 'Hours'}/
    %input.edit-payment-description{:type => 'textfield', :value => "#{payment.description}", :name => 'payment-description', :placeholder => "Description"}/
    %input.edit-payment-start_date{:type => 'textfield', :value => "#{payment.start_date.strftime("#{ActiveSupport::Inflector.ordinalize(day)} %b %Y")}", :name => 'payment-start_date'}/
    %a.save-payment.small-button{:href => "#"} Save
    %span.or or
    %a.cancel-link{:href => "#"} Cancel
    - if defined? ff and @project.new_record?
      = ff.hidden_field :rate, value: payment.rate
      = ff.hidden_field :number_of_hours, value: payment.number_of_hours
      = ff.hidden_field :description, value: payment.description
      = ff.hidden_field :start_date, value: payment.start_date
      = ff.hidden_field :recurring, value: payment.recurring
      = ff.hidden_field :completed, value: payment.completed

app/views/payments/_payments.html.haml
= render :partial => 'projects/form_payments', :locals => {:payments => payments}
:javascript
  $('#payments_container').show()

app/views/payments/_plain_payment.html.haml
%li.single-payment{:id => "payment_#{payment.id}", :class => "payment-"+completed_text(payment).downcase}
  .payment-completed-icon{:class => completed_class(payment), :payment_id => payment.id}
    %span= completed_text(payment)
  .payment-value
    =p payment.total_value 
  .payment-title
    .payment-project-name
      = link_to payment.project.try(:name), payment.project
    .payment-name
      = payment.description
  .payment-date
    = payment.start_date.strftime("#{ActiveSupport::Inflector.ordinalize(payment.start_date.day)} %b %Y")
  .payment-type
    = surround '(', ')' do
      = payment.recurring
  .sort-order{:order => payment.start_date.to_i}

app/views/payments/create.js.erb
<% unless @errors %>
  // show new payment node
  <% @payments.each do |payment| %>
    var paymentNode = $("<%= escape_javascript(render(payment)) %>")//.hide()
    $('#payments-list').append(paymentNode)
    paymentNode.show('fast')
  <% end %>

  // Clear payment form values
  $("#payment-type").find("input").attr('value', '')
  $("#payment-completed-href").attr('checked', false)

  // Notify user
  $.ctNotify("Payment created", 'message')

  $("#active-projects-container").html("<%= escape_javascript(render_project_overview(@project, true))%>")

  $(".edit-payment-start_date").datepicker({
    dateFormat: 'dth M yy',
    onSelect: function(dateText, inst) {
        this.value = customFormatString(dateText)
    }
  });
  sortPayments()
<% else %>
  $.ctNotify("<%= @errors%>", 'error')
<% end %>

app/views/payments/destroy.js.erb
$("#payment_<%= @payment.id %>").hide('fast').remove()
$.ctNotify('Payment deleted')

$("#active-projects-container").html("<%= escape_javascript(render_project_overview(@payment.project, true))%> ")

sortPayments()

app/views/payments/index.html.haml
- sidebar "add_buttons", "tip"
- content_for :head do
  = javascript_include_tag 'payments/payments_index.js'
  = javascript_include_tag 'payments/payments.js'

#payments.dashboard-project
  #payments-container
    %h2.open
      Payments
    .add-payment-icon Payments
    .projects-header.list-filters
      = render 'list_filters', :payments => @payments.to_a
    .projects-header#payments-header
      = render 'list_header', :payments => @payments.to_a
  %ul#payments-list
    - @payments.each do |payment|
      = render 'plain_payment', :payment => payment

:javascript
  updatePaymentCompletedTooltips()
  window.notSortPayments = true;

app/views/payments/index.js.erb
$('#payments-list').html('<%= escape_javascript(render(:partial => "plain_payment", :collection => @payments, :as => :payment))%>')
$("#payments-header").html('<%= escape_javascript(render("list_header", :payments => @payments.to_a)) %>')

updatePaymentCompletedTooltips();

app/views/payments/update.js.erb
$("#payment_<%= @payment.id %> div[payment_id='<%= @payment.id %>']").removeClass("payment-not-completed").removeClass("payment-completed")
<% if @is_updated == true %>
  $.ctNotify("Payment updated!")
<% else %> 
  <% if @payment.completed %>
    $("#payment_<%= @payment.id %> div[payment_id='<%= @payment.id %>']").addClass('payment-completed')
    $.ctNotify("Payment has been completed")
  <% else %>
    $("#payment_<%= @payment.id %> div[payment_id='<%= @payment.id %>']").addClass('payment-not-completed')
    $.ctNotify("Payment is pending")
  <% end %>
<% end %> 

<% @project = @payment.project %>

<% if @plain %>
  $("#payments-header").html("<%= escape_javascript(render('list_header', payments: @payments.to_a))%>")
  <% if @status.present? %>
    <% if @status == (@payment.completed ? '1' : '0') %>
      $("#payment_<%= @payment.id %>").replaceWith("<%= escape_javascript(render('plain_payment', payment: @payment)) %>")
    <% else %>
      $("#payment_<%= @payment.id %>").hide()
    <% end %>
  <% end %>
<% else %>
  $("#active-projects-container").html("<%= escape_javascript(render_project_overview(@payment.project, true))%> ")
  $("#payment_<%= @payment.id %>").replaceWith("<%= escape_javascript(render(@payment)) %>")
<% end %>

$(".edit-payment-start_date").datepicker({
  dateFormat: 'dth M yy',
  onSelect: function(dateText, inst) {
    this.value = customFormatString(dateText)
  }
});

<% unless @plain %>
  sortPayments()
<% end %>

updatePaymentCompletedTooltips();