config/routes.rb
Bacon::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get "login", to: "devise/sessions#new", as: :login
    get "logout", to: "devise/sessions#destroy", as: :logout
  end

  match '/organizations/check_url' => 'organizations#check_url'
  match '/organizations/switch_month' => 'organizations#switch_month'
  match '/account' => 'users#edit'
  match '/upload' => 'organizations#upload'
  match '/welcome' => 'organizations#welcome'
  match '/organizations/:id/delete_demo_projects' => 'organizations#delete_demo_projects', as: :delete_demo_projects
  match '/users/:id/delete_account' => 'users#delete_account', as: :delete_account

  resource :user, only: [:edit] do
    collection do
      put 'update'
    end
  end

  resources :plans

  resources :organizations, :except => [:index] do
    get "search" => 'organizations#search', :on => :member
    # post :upload, :on => :member
    get ":year/:month" => "organizations#show", constraints: {
        year:       /\d{4}/,
        month:      /\d{1,2}/
    }
  end
  # resources :organizations, :except => [:index] do
  resources :projects do
    post :update_status
    resources :payments, :only => :create
    resources :notes, :only => [:create, :destroy, :update]
    resources :project_contacts
  end
  resources :contacts do
    post :filter, :on => :collection
    get :hover, :on => :member
  end
  resources :categories do
    post :update_color, :on => :member
  end
  # end
  resources :payments
  resources :notes

  match '/api/create_user' => 'api#create_user'
  match '/api/update_user' => 'api#update_user'
  match '/api/delete_user' => 'api#delete_user'
  match '/api/users/validate' => 'api#validate_user'
  match '/api/check_url' => 'api#check_url'

  match '/feedbacks' => 'feedbacks#index'
  root :to => 'organizations#show'

  default_url_options :host => 'incomehawkapp.com'
end

app/models/category.rb
class Category < ActiveRecord::Base

  ## associations ##
  belongs_to :organization
  has_many :projects

  ## validations ##
  validates :name, :color, :organization_id, presence: true
  validates :name, uniqueness: { scope: :organization_id }

  ## options ##
  attr_accessible :name, :color, :organization_id

  ## named scopes ##
  scope :search_for, -> (term) { term = "%#{term.downcase}%"
    where(["LOWER(name) LIKE ?", term]) }

  ## methods ##
  def to_s
    name
  end

  class << self
    def colorname2color(color)
      clrs = {'blue'        =>  '#0054a6','light-blue'  =>  '#0074bd','cyan'        =>  '#0093bd',
      'sky-blue'    =>  '#00aef0','eggplant'    =>  '#00aef0','fuxia'       =>  '#00aef0',
      'purple'      =>  '#6500bd','red'         =>  '#f81d46','maroon'      =>  '#f81d46',
      'dark-green'  =>  '#00612d','light-green' =>  '#8dc73f','orange'      =>  '#f8941d',
      'brown'       =>  '#603913','gray'        =>  '#52616b','black'       =>  'black' }
      clrs[color]
    end

    def json_data(categories)
      categories.collect do |cat|
        { label: cat.name, category: 'Categories', desc: "projects: #{cat.projects.count}" }
      end
    end

  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  inherit_resources
  before_filter :fetch_tabs
  layout 'garden'
  nested_belongs_to :organization


  def index
    @categories = @organization.categories
    respond_to do |format|
      format.html
      format.js {
        render :index, :layout => false,  :content_type => 'text/html'
      }
    end
  end

  def show
    @category = @organization.categories.find(params[:id])
  end

  def new
    @categories = @organization.categories
    @category = Category.new
    respond_to do |format|
      format.html
      format.js { render :index, :layout => false,  :content_type => 'text/html' }
    end
  end

  def create
    params[:category][:color] ||= '#cc2222'
    @category = @organization.categories.build(params[:category])
    if @category.save
      @categories = @organization.categories
      respond_to do |format|
        format.html
        format.js
      end
    else
      respond_to do |format|
        format.js { render :json => 'fail'}
      end
    end
  end

  def edit
    @category = @organization.categories.find(params[:id])
  end

  def update
    @category = @organization.categories.find(params[:id])
    if params[:category][:color]
      params[:category][:color] = Category.colorname2color(params[:category][:color])
      @update_color = 1
    elsif params[:category][:name]
      @update_name = 1
    end
    if @category.update_attributes(params[:category])
      respond_to do |format|
        format.js
      end
    else
      render :action => 'edit'
    end
  end

  def update_color
    @category = @organization.categories.find(params[:id])
    @category.update_attributes(params[:category])
    if @category.save
      respond_to do |format|
        format.js
      end
    else
      render :action => 'edit'
    end
  end

  def destroy
    @category = @organization.categories.find(params[:id])
    if @category.projects.count == 0
      @id = @category.id
      @category.destroy
    else
      @id = false
    end

    respond_to do |format|
      format.html {redirect_to categories_url}
      format.js
    end

  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories.haml
%table#categories_list{:cellpadding => '10px', :cellspacing => '10px'}
  %tr
    %th
    %th
    %th
  - for category in categories
    = render :partial => 'categories/category', :locals => {:category => category}

app/views/categories/_category.html.haml
%li.category-item{:id => "category_#{category.id}"}
  %a.color-select-widget
    %span.selected-color{:style => "background: none repeat scroll 0 0 #{category.try(:color)}"}
    %span.dropdown-arrow Arrow
    %span.hide-border
    .color-grid{:category_id => "#{category.id}", :organization_id => "#{category.organization.id}"}
      %ul.color-selection
        %li
          %span.color.blue
        %li
          %span.color.light-blue
        %li
          %span.color.cyan
        %li
          %span.color.sky-blue
        %li
          %span.color.eggplant
      %ul.color-selection
        %li
          %span.color.fuxia
        %li
          %span.color.purple
        %li
          %span.color.red
        %li
          %span.color.maroon
        %li
          %span.color.orange
      %ul.color-selection
        %li
          %span.color.brown
        %li
          %span.color.dark-green
        %li
          %span.color.light-green
        %li
          %span.color.gray
        %li
          %span.color.black
  %h4.category-name= category.name
  .update-category-wrapper{:category_id => "#{category.id}", :organization_id => "#{category.organization.id}"}
    %input.edit-category-name{:type => "textfield", :value => "#{category.name}"}/
    %a.save-category-name.small-button{:href => "#"} Save
    %span.or or
    %a.cancel-link{:href => "#"} Cancel
  .are-you-sure-wrapper
    %span.are-you-sure Are you sure?
    = link_to "Delete Category", category, :method => :delete, :remote => true, :class => 'small-button'
    %span.or or
    %a.cancel-link{:href => "#"} Cancel
  
  = link_to "Edit", '#', :class => 'edit-link'
  = link_to "Delete", '#', :class => 'delete-category delete-button-small'

app/views/categories/_form.html.haml
= form_for @category do |f|
  = f.error_messages
  %p
    = f.label :name
    %br/
    = f.text_field :name
  %p
    = f.label :color
    %br/
    = f.text_field :color
  %p= f.submit

app/views/categories/create.js.erb
$('#category-list').prepend( "<%= escape_javascript(render :partial => 'categories/category', :locals => {:category => @category}) %>" )
// $('#category-list .category').last().animate({ backgroundColor: "yellow" }, 3000).animate({ backgroundColor: "" }, 3000)
$('#input-add-category-wrapper input').attr('value', '')

$('#category_<%= @category.id%> .colorpicker').colorPicker();
$('#<%= @category.id%>').live('change', function() {
  var cid = $(this).attr('id');
  $("#edit_category_"+cid).submit();
})

// Add new category to project category select
$("<option></option>").
attr("value",<%= @category.id%>).
text('<%= @category.name%>').insertAfter($('#project-categories').children()[1]);

$('#project-categories').chosen().trigger("liszt:updated")

app/views/categories/destroy.js.erb
<% if @id %>
  $('#category_<%= @id %>').hide(200);
  $("#project_category_id option[value='<%= @id %>']").remove()
  $.ctNotify("Category deleted")
<% else %>
  $('#category_<%= @category.id %> .are-you-sure-wrapper').hide('fast')
  $('#category_<%= @category.id %> .update-category-wrapper').hide('fast')
  $('#category_<%= @category.id %> .category-name').show('fast')
  $('#category_<%= @category.id %> .delete-button-small').show()
  $('#category_<%= @category.id %> .edit-link').show()

  $.ctNotify("Cannot delete this category because there are still projects using it. Please updated projects and try again.")
<% end %>

// update project category select
$("#project-categories option[value='<%= @category.id %>']").remove();

$('#project-categories').chosen().trigger("liszt:updated")

app/views/categories/edit.html.haml
- title "Edit Category"
= render 'form'
%p
  = link_to "Show", @category
  |
  \#{link_to "View All", categories_path}

app/views/categories/index.html.haml
#edit-categories.lightbox
  %a.close-button{:href => "#"} Close
  %h2 Edit Categories
  %p
    You may add more categories or edit existing categories here.
    %br>/
    Editing a category will affect all existing projects.
  .add-category-wrapper
    = semantic_form_for Category.new, :url => categories_path( :format => :js), :remote => true do |fc|
      #input-add-category-wrapper.form-item
        %label.form-add-category-label{:for => "input-add-category"} Add a new Category
        %input#input-add-category.textfield{:type => "text", :name => "category[name]"}/
        %a#add-category-button.small-button{:href => "#"} Add
  %ul#category-list
    = render :partial => 'categories/categories', :locals => {:categories => @categories}

  %a.done{:href => "#"} I'm Done

app/views/categories/new.html.haml
- title "New Category"
= render 'form'
%p= link_to "Back to List", categories_path

app/views/categories/new.js.haml
%h2 EDIT CATEGORIES
%p
  you may add more categories or edit you excisting categories here. Editing a category will affect all existing projects.

.categories_add_form
  %h3 Add a new Category
  = semantic_form_for Category.new, :remote => true do |fc|
    = fc.input :name, :input_html => {:id => "new_category_name"}
    = fc.submit "Add"

:plain
  <script charset="utf-8, type="text/javascript">
    $(function() {
      $('.colorpicker').colorPicker();
      $('input.colorpicker').live('change', function() {
        var cid = $(this).attr('id');
        $("#edit_category_"+cid).submit();
      })
    })
  </script>
= render :partial => 'categories/categories', :locals => {:categories => @categories}

app/views/categories/show.html.haml
- title "Category"
%p
  %strong Name:
  = @category.name
%p
  %strong Color:
  = @category.color
%p
  = link_to "Edit", edit_category_path(@category)
  |
  \#{link_to "Destroy", @category, :confirm => 'Are you sure?', :method => :delete} |
  \#{link_to "View All", categories_path}

app/views/categories/update.js.erb
<% if @update_color %>
  $("#category_<%= @category.id%>").find('.selected-color').css('background', 'none repeat scroll 0 0 <%= @category.color %>')
<% elsif @update_name %>
  $("#project_category_id option[value='<%= @category.id %>']").text('<%= @category.name %>')
  $("#category_<%= @category.id%>").find('.category-name').text('<%= @category.name %>')
<% end %>
$.ctNotify('Category <%= @category.name %> updated', 'message')

// update project category select
$("#project-categories option[value='<%= @category.id %>']").text('<%= @category.name %>')

$('#project-categories').chosen().trigger("liszt:updated")

app/views/categories/update_color.js.erb
$("#category_<%= @category.id%>").find('.selected-color').css('background', 'none repeat scroll 0 0 <%= @category.color %>')
$.ctNotify('Category <%= @category.name %> updated', 'message')